#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

rg -q "BT_GAP_SCAN_FAST_INTERVAL" "$repo_root/src/ble_time_sync_client.c"
rg -q "BT_GAP_SCAN_FAST_WINDOW" "$repo_root/src/ble_time_sync_client.c"
rg -q "scan_seen" "$repo_root/src/ble_time_sync_client.c"
rg -q "scan_match" "$repo_root/src/ble_time_sync_client.c"
rg -q "scan_reject_type" "$repo_root/src/ble_time_sync_client.c"
rg -q "scan_reject_filter" "$repo_root/src/ble_time_sync_client.c"
rg -q "connect_attempts" "$repo_root/src/ble_time_sync_client.c"
rg -q "connect_failures" "$repo_root/src/ble_time_sync_client.c"
rg -q "ble_time_sync_client_get_scan_stats" "$repo_root/src/ble_time_sync_client.h"
rg -q "BT_GAP_ADV_FAST_INT_MIN_2" "$repo_root/src/ble_time_sync.c"
rg -q "BT_GAP_ADV_FAST_INT_MAX_2" "$repo_root/src/ble_time_sync.c"
rg -q "\"ble_scan:" "$repo_root/src/status.c"
rg -q "seen=%u" "$repo_root/src/status.c"
rg -q "match=%u" "$repo_root/src/status.c"
rg -q "type_drop=%u" "$repo_root/src/status.c"
rg -q "filter_drop=%u" "$repo_root/src/status.c"
rg -q "conn_req=%u" "$repo_root/src/status.c"
rg -q "conn_fail=%u" "$repo_root/src/status.c"
rg -q "ble_scan" "$repo_root/README.md"
rg -q "conn_fail" "$repo_root/README.md"
