#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include <stdint.h>

#define RADIO_BRIDGE_GROUP_ID_VALUE CONFIG_RADIO_BRIDGE_GROUP_ID
#define RADIO_BRIDGE_UART_BAUDRATE_VALUE CONFIG_RADIO_BRIDGE_UART_BAUDRATE
#define RADIO_BRIDGE_SYNC_INTERVAL_US_VALUE CONFIG_RADIO_BRIDGE_SYNC_INTERVAL_US
#define RADIO_BRIDGE_UART_RING_SIZE_VALUE CONFIG_RADIO_BRIDGE_UART_RING_SIZE
#define RADIO_BRIDGE_MAX_SLAVES_VALUE 3u
#define TIME_SYNC_PPS_PERIOD_US_VALUE 1000000u
#define TIME_SYNC_PPS_WIDTH_US_VALUE CONFIG_TIME_SYNC_PPS_WIDTH_US
#define TIME_SYNC_STATUS_INTERVAL_MS_VALUE CONFIG_TIME_SYNC_STATUS_INTERVAL_MS
#ifdef CONFIG_TIME_SYNC_LED_HEARTBEAT_PERIOD_MS
#define TIME_SYNC_LED_HEARTBEAT_PERIOD_MS_VALUE CONFIG_TIME_SYNC_LED_HEARTBEAT_PERIOD_MS
#else
#define TIME_SYNC_LED_HEARTBEAT_PERIOD_MS_VALUE 1000u
#endif

#if CONFIG_RADIO_BRIDGE_GROUP_ID == 0 || CONFIG_RADIO_BRIDGE_GROUP_ID == UINT32_MAX
#error "group id 0 and UINT32_MAX are reserved"
#endif
_Static_assert(sizeof(CONFIG_RADIO_BRIDGE_GROUP_KEY) == 33,
	       "group key must contain exactly 32 hexadecimal characters");
#if CONFIG_RADIO_BRIDGE_UART_RING_SIZE < 16384
#error "UART rings must be at least 16 KiB"
#endif
#endif
