#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include <zephyr/kernel.h>

#define TIME_SYNC_NETWORK_ID_VALUE CONFIG_TIME_SYNC_NETWORK_ID
#define TIME_SYNC_RF_CHANNEL_VALUE CONFIG_TIME_SYNC_RF_CHANNEL
#define TIME_SYNC_INTERVAL_US_VALUE CONFIG_TIME_SYNC_INTERVAL_US
#define TIME_SYNC_PPS_PERIOD_US_VALUE CONFIG_TIME_SYNC_PPS_PERIOD_US
#define TIME_SYNC_PPS_WIDTH_US_VALUE CONFIG_TIME_SYNC_PPS_WIDTH_US
#define TIME_SYNC_RADIO_DELAY_US_VALUE CONFIG_TIME_SYNC_RADIO_DELAY_US
#define TIME_SYNC_RADIO_TXEN_TO_ADDRESS_US_VALUE CONFIG_TIME_SYNC_RADIO_TXEN_TO_ADDRESS_US
#define TIME_SYNC_STATUS_INTERVAL_MS_VALUE CONFIG_TIME_SYNC_STATUS_INTERVAL_MS
#define TIME_SYNC_LED_HEARTBEAT_PERIOD_MS_VALUE CONFIG_TIME_SYNC_LED_HEARTBEAT_PERIOD_MS

#if defined(CONFIG_TIME_SYNC_ROLE_MASTER) && defined(CONFIG_TIME_SYNC_ROLE_SLAVE)
#error "Select only one time sync role"
#endif

#if !defined(CONFIG_TIME_SYNC_ROLE_MASTER) && !defined(CONFIG_TIME_SYNC_ROLE_SLAVE)
#error "Select a time sync role"
#endif

#endif
